## Topics

- Data Preprocessing: Handling NA values
- Linear Regression Using Multiple variables

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [6]:
df= pd.read_csv("C:/Users/ezhil/Desktop/BITTU DOCUMENTS/Code basics/ml 2 codebasics/homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

to handle NaN in the above column, let us take mean and put it in the place of NaN.

In [7]:
df.bedrooms.median()

3.5

 to keep it as integer- whole number we are going to impot math module

In [11]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [13]:
df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [14]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

Now we need to assign the values of new datas with the original data frame

In [17]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

Data preprocessing is done, which means data cleaning, fix the errors, handle missing data and then train machine learning model

Remeber always first create object and then fit data

In [21]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms','age']], df.price)
#fit method is used often to train your model
# use 2 bracs to cretae your dataframe with existing data frame
#independent variables are area, bedrooms, age
# dependent varible is price

LinearRegression()

In [107]:
reg.coef_ #coefficient

array([2812.95487627, 1845.70596798, 2205.24017467])

price = m1*area + m2*bedrooms + m3*age

m1, m2, m3 are coefficients

area, bedrooms, age are independent variables 

price dependent variables

In [108]:
reg.intercept_ # intercept

17737.26346433768

predict home prices

- 3000 sq.ft area, 3 bedrooms, 40 year old
- 2500 sq.ft area, 4 bedrooms, 5 year old

In [28]:
reg.predict([[3000, 3, 40]])
# same 3000sq.ft 4 bedroom and 15 age is 565,000$
# our prediction is less depending on years

array([444400.])

In [30]:
reg.predict([[3000, 3, 15]])
# it is little bit skewed, but we tend to get whole path number

array([615025.])

In [33]:
#predict home prices
# 3000 sq.ft area, 3 bedrooms, 40 year old

reg.predict([[3000, 3, 40]])

array([444400.])

In [32]:
137.25*3000+-26025*3+-6825*40+383724.9999999998

444399.9999999998

In [34]:
# predict home prices
# 2500 sq.ft area, 4 bedrooms, 5 year old
reg.predict([[2500,4,5]])

array([588625.])

# Excercise file

In [94]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [44]:
df = pd.read_csv("C:/Users/ezhil/Desktop/BITTU DOCUMENTS/Code basics/ml 2 codebasics/hiring.csv")
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [45]:
df.test_score.median()

8.0

## These are done for checking

import math
median_test_score = math.floor(df.test_score.median())
median_test_score

In [47]:
median_test_score = df.test_score.median()
median_test_score

8.0

In [48]:
df.test_score = df.test_score.fillna(median_test_score)
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In experience let's assume the NaN value to be Zero

In [52]:
df.experience= df.experience.fillna('Zero')
df

experience  test_score  interview_score  salary
0       Zero         8.0                9   50000
1       Zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [experience column] Convert string to number, because linear regression won't work in strings and then

Predict the following datas

- 2yr experience, 9 test score, 6 interview score
- 12yr experience, 10 test score, 10 interview score

In [63]:
df.experience.replace(['Zero', 'five', 'two', 'seven', 'three', 'ten', 'eleven'], [0,5,2,7,3,10,11])

0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64

In [64]:
df

experience  test_score  interview_score  salary
0       Zero         8.0                9   50000
1       Zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [104]:
df.experience = df.experience.replace(['Zero', 'five', 'two', 'seven', 'three', 'ten', 'eleven'], [0,5,2,7,3,10,11])
df
#lastly, while checking answer in the github, the below code is used
#df.experience = df.experience.apply(w2n.word_to_num)
# look into the last module

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

Now we have changed word to numbers, now let's Predict the following datas:

- 2yr experience, 9 test score, 6 interview score
- 12yr experience, 10 test score, 10 interview score


 Let's train our model

- first we'll create object
- second we'll fit datas

In [67]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score', 'interview_score']], df.salary)

LinearRegression()

In [105]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [106]:
reg.intercept_

17737.26346433768

- First prediction, - 2yr experience, 9 test score, 6 interview score


In [68]:
reg.predict([[2,9,6]])

array([53205.96797671])

- Second prediction, - 12yr experience, 10 test score, 10 interview score

In [69]:
reg.predict([[12,10,10]])

array([92002.18340611])

## Certain things to be noted and which I learned:

df.experience = df.experience.apply(w2n.word_to_num)

for this code we need to import a package,

the package is, [from word2number import w2n]

- from word2number import w2n
- but unfortunately it shows no module found.

## solution found

- we can installed a package first then we are using it, now it runs successfully

In [103]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [101]:
from word2number import w2n

In [95]:
df = pd.read_csv("C:/Users/ezhil/Desktop/BITTU DOCUMENTS/Code basics/ml 2 codebasics/hiring.csv")
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [97]:
df.experience = df.experience.fillna('zero')
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [102]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000