In this tutorial, topics

we are goint to continue our linear regression tutorial with,


categorial, dummy variables, one hot conding

- Using pandas get_dummies
- Using sklearn OneHotEncod

## first method Using pandas get_dummies

## Problem to be solved

- with 3400 sq.ft area in west windsor

- 2800 sq.ft home in robbinsville

- we should calculate according to the area this is the new thing to be handled


In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("C:/Users/ezhil/Desktop/BITTU DOCUMENTS/Code basics/Machine learning from tutorial 3/ml 6/homeprices.csv")
df

town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [6]:
# how to handle text data in numeric model, because ML is good in handling numeric data

# one way to do this is integer encoding or label encoding, where we convert name of the town to certain number.
# but the problem is it will asuume that one town is less than the other likethat
# these variables are nominal variables which comes under categorical variables
# the second is ordinal egs(satisfies, neutral, dissatisfied, graduate, phd, masters, high, medium, low)

# for nominal variables we are using a technique, called one hot encoding
# one hot encoding works by creating seperate coulmns for each of our categories and assigning a binary value(0,1)
 


In [7]:
dummies = pd.get_dummies(df.town)
dummies

monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [8]:
merged = pd.concat([df,dummies], axis='columns')
merged

town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [9]:
# now drop the town column, then one of the dummy variable coulmn
# google dummy variable trap
# whenever one variable can be derived from rest of the variables, these variables are said to be muticolinear
# this multicolinearity creates the problem with dummy variable trap, which mess up with ML model
# so a thumb rule is, we have to drop one of the dummy variable column


In [10]:
final = merged.drop(['town', 'west windsor'], axis='columns')
final
# remember sklear linear regreesion drops dummy variables automatically.
# but in general, it's a good pratice to drop the dummy variables

area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

In [11]:
# we have created an object for linear regression model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [12]:
# we need to assign a and y for training
# x all columns except price column
# y is price column
x = final.drop('price', axis='columns')
x

area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [13]:
y = final.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [14]:
# model.fit we ar eactually training our ML model
# in real life situation we have lot's and lot's of data, where training data takes a little time

model.fit(x,y)

LinearRegression()

In [15]:
model.predict([[2800,0,1]]) # price in robinsville

array([590775.63964739])

In [16]:
# price in west windsor
model.predict([[3400,0,0]])

array([681241.66845839])

In [17]:
# to know how accurate our model is
model.score(x,y)
# 0.957 means our model is 95% accurate
# if 1 means 100% accurate

0.9573929037221873

## One Hot Encoder method

In [18]:
# let's use one hot encoder method, for that we need to label encoder at the town column 

In [151]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#Label encoder class object is ready

In [152]:
dfle = df # creating a new dataframe
le.fit_transform(dfle.town) 
# using label encoder to fit and transform
# fit and transform means, it takes label coulmn as input

array([0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 1], dtype=int64)

In [153]:
dfle.town = le.fit_transform(dfle.town) 
dfle

town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [154]:
# once done, now we are creating x variable
#x is the training data set
# y is our dependent variable

# .values is used because we need x as a 2-dimensional array.

x = df[['town', 'area']].values
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [155]:
y = dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [172]:
# code from datascience stack exchange
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_x = LabelEncoder()
x[:, 0] = labelencoder_x.fit_transform(x[:, 0])
transformer = ColumnTransformer([('one_hot_encoder', OneHotEncoder(), [0])],remainder='passthrough')
x = np.array(transformer.fit_transform(x), dtype= np.float64)
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [170]:
x = x[:,1:]
x

array([[0.0e+00, 2.6e+03],
       [0.0e+00, 3.0e+03],
       [0.0e+00, 3.2e+03],
       [0.0e+00, 3.6e+03],
       [0.0e+00, 4.0e+03],
       [1.0e+00, 2.6e+03],
       [1.0e+00, 2.8e+03],
       [1.0e+00, 3.3e+03],
       [1.0e+00, 3.6e+03],
       [0.0e+00, 2.6e+03],
       [0.0e+00, 2.9e+03],
       [0.0e+00, 3.1e+03],
       [0.0e+00, 3.6e+03]])

In [167]:
model.fit(x,y)

LinearRegression()

In [169]:
model.predict([[1,0,3400]])

array([8.71344872])

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x = LabelEncoder()
x[:,0] = labelencoder_x.fit_transform(x[:, 0])
ohe = OneHotEncoder(categorical_features[0] )
x = ohe.fit_transform(x).toarray()


# encoding the categorical data, doesn't works

from sklearn.preprocessing import LabelEncoder

labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_x.fit_transform(X[:,0])

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categorical_features[0])


x = x[:,1:]
x

model.fit(x,y)

model.predict([[1,0,2800]])

# after finding that the actual tutorial code shows some error
# searching into comment section we found this code, but doesn't works

from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("town", OneHotEncoder(),[0])], remainder='passthrough') 

x = ct.fit_transform(x)
x

x = x[:,1:]
x

model.fit(x,y)

model.predict([[1,0,2800]])

##  this one is also found in comment section
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(
[('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],
remainder='passthrough')
x = ct.fit_transform(x)
x

model.fit(x,y)

model.predict([1,0,2800])

# this one from comment section

ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],
    remainder='passthrough' 
)
X = ct.fit_transform(X)
X

## Excercise file

- predict price of a mercedez benz that is 4 yr old with mileage 45000

- predict price of a BMW X5 that is 7 yr old with mileage 86000

- tel me the score (accuracy) of your model.(hint : use LinearRegression(.score())

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/ezhil/Desktop/BITTU DOCUMENTS/Code basics/Machine learning from tutorial 3/ml 6/carprices.csv")
df

Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [8]:
df.dummies(['carmodel'], axis='columns')

AttributeError: 'DataFrame' object has no attribute 'dummies'