## Excercise

Train SVM Classifier using sklearn digits dataset(i.e, from sklearn.datasets import load_digits) and then,

- measure accuracy of your model using different kernels such as rbf and linear.
- Tune your model further using regularization and gamma parameters and try to come up with highest accuracy score
- use 80% of samples as training data size

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
from sklearn.datasets import load_digits
d = load_digits()

In [9]:
dir(d)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [10]:
df = pd.DataFrame(d.data)
df.head()

0    1    2     3     4     5    6    7    8    9   ...   54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [11]:
d.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#d.feature_names

In [13]:
# let's append feature_ names to columns

In [30]:
df = pd.DataFrame(d.data, columns=d.feature_names)
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        5.0        0.0   
3        0.0        0.0        0.0        8.0  ...        9.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0        0.0        0.0        6.0       13.0       10.0        0.0   
1        0.0        0.0        0.0       11.0       16.0       10.0   
2        0.0        0.0        0.0        3.0       11.0       16.0   
3        0.0        0.0        7.0       13.0       13.0        9.0   
4        0.0        0.0        0.0        2.0       16.0        4.0   

   pixel_7_6  pixel_7_7  
0        0.0        0.0  
1        0.0        0.0  
2        9.0        0.0  
3        0.0        0.0  
4        0.0        0.0  

[5 rows x 64 columns]

In [32]:
df.shape

(1797, 64)

In [34]:
d.target

array([0, 1, 2, ..., 8, 9, 8])

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
0        0.0        6.0       13.0       10.0        0.0        0.0   
1        0.0        0.0       11.0       16.0       10.0        0.0   
2        0.0        0.0        3.0       11.0       16.0        9.0   
3        0.0        7.0       13.0       13.0        9.0        0.0   
4        0.0        0.0        2.0       16.0        4.0        0.0   

   pixel_7_7  target  
0        0.0       0  
1        0.0       1  
2        0.0       2  
3        0.0       3  
4        0.0       4  

[5 rows x 65 columns]

In [38]:
d.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
1         0.0        0.0        0.0       12.0       13.0        5.0   
11        0.0        0.0        0.0        0.0       14.0       13.0   
21        0.0        0.0        0.0        2.0       16.0       16.0   
42        0.0        0.0        0.0        0.0       12.0        5.0   
47        0.0        0.0        0.0        1.0       11.0        9.0   

    pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
1         0.0        0.0        0.0        0.0  ...        0.0        0.0   
11        1.0        0.0        0.0        0.0  ...        0.0        0.0   
21        2.0        0.0        0.0        0.0  ...        0.0        0.0   
42        0.0        0.0        0.0        0.0  ...        0.0        0.0   
47        0.0        0.0        0.0        0.0  ...        0.0        0.0   

    pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
1         0.0        0.0       11.0       16.0       10.0        0.0   
11        0.0        0.0        1.0       13.0       16.0        1.0   
21        0.0        0.0        2.0       12.0       15.0        4.0   
42        0.0        0.0        3.0       16.0        8.0        0.0   
47        0.0        0.0        2.0       14.0        6.0        0.0   

    pixel_7_7  target  
1         0.0       1  
11        0.0       1  
21        0.0       1  
42        0.0       1  
47        0.0       1  

[5 rows x 65 columns]

In [43]:
d.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
df = pd.DataFrame(d.data, d.target)
df.head()

0    1    2     3     4     5    6    7    8    9   ...   54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [48]:
df['target'] = d.target
df.head(20)

0    1     2     3     4     5     6    7    8     9  ...   55   56   57  \
0  0.0  0.0   5.0  13.0   9.0   1.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
1  0.0  0.0   0.0  12.0  13.0   5.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
2  0.0  0.0   0.0   4.0  15.0  12.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
3  0.0  0.0   7.0  15.0  13.0   1.0   0.0  0.0  0.0   8.0  ...  0.0  0.0  0.0   
4  0.0  0.0   0.0   1.0  11.0   0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
5  0.0  0.0  12.0  10.0   0.0   0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
6  0.0  0.0   0.0  12.0  13.0   0.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
7  0.0  0.0   7.0   8.0  13.0  16.0  15.0  1.0  0.0   0.0  ...  0.0  0.0  0.0   
8  0.0  0.0   9.0  14.0   8.0   1.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
9  0.0  0.0  11.0  12.0   0.0   0.0   0.0  0.0  0.0   2.0  ...  0.0  0.0  0.0   
0  0.0  0.0   1.0   9.0  15.0  11.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
1  0.0  0.0   0.0   0.0  14.0  13.0   1.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
2  0.0  0.0   5.0  12.0   1.0   0.0   0.0  0.0  0.0   0.0  ...  2.0  0.0  0.0   
3  0.0  2.0   9.0  15.0  14.0   9.0   3.0  0.0  0.0   4.0  ...  0.0  0.0  2.0   
4  0.0  0.0   0.0   8.0  15.0   1.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
5  0.0  5.0  12.0  13.0  16.0  16.0   2.0  0.0  0.0  11.0  ...  0.0  0.0  4.0   
6  0.0  0.0   0.0   8.0  15.0   1.0   0.0  0.0  0.0   0.0  ...  2.0  0.0  0.0   
7  0.0  0.0   1.0   8.0  15.0  10.0   0.0  0.0  0.0   3.0  ...  0.0  0.0  0.0   
8  0.0  0.0  10.0   7.0  13.0   9.0   0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
9  0.0  0.0   6.0  14.0   4.0   0.0   0.0  0.0  0.0   0.0  ...  2.0  0.0  0.0   

     58    59    60    61    62   63  target  
0   6.0  13.0  10.0   0.0   0.0  0.0       0  
1   0.0  11.0  16.0  10.0   0.0  0.0       1  
2   0.0   3.0  11.0  16.0   9.0  0.0       2  
3   7.0  13.0  13.0   9.0   0.0  0.0       3  
4   0.0   2.0  16.0   4.0   0.0  0.0       4  
5   9.0  16.0  16.0  10.0   0.0  0.0       5  
6   1.0   9.0  15.0  11.0   3.0  0.0       6  
7  13.0   5.0   0.0   0.0   0.0  0.0       7  
8  11.0  16.0  15.0  11.0   1.0  0.0       8  
9   9.0  12.0  13.0   3.0   0.0  0.0       9  
0   1.0  10.0  13.0   3.0   0.0  0.0       0  
1   0.0   1.0  13.0  16.0   1.0  0.0       1  
2   3.0  11.0   8.0  13.0  12.0  4.0       2  
3  12.0  12.0  13.0  11.0   0.0  0.0       3  
4   0.0  10.0  15.0   4.0   0.0  0.0       4  
5  15.0  16.0   2.0   0.0   0.0  0.0       5  
6   0.0   7.0  15.0  16.0  11.0  0.0       6  
7   0.0  11.0   9.0   0.0   0.0  0.0       7  
8  11.0  14.0   5.0   0.0   0.0  0.0       8  
9   7.0  16.0  16.0  13.0  11.0  1.0       9  

[20 rows x 65 columns]

In [49]:
x = df.drop('target', axis='columns')
y = df.target

In [53]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [55]:
from sklearn.svm import SVC
rbf_model = SVC(kernel='rbf')

In [57]:
len(x_train)

1257

In [59]:
len(x_test)

540

In [58]:
len(x)

1797

In [60]:
rbf_model.fit(x_train, y_train)

SVC()

In [61]:
rbf_model.score(x_test,y_test)

0.987037037037037

In [62]:
rbf_model = SVC(kernel='linear')

In [63]:
rbf_model.fit(x_train, y_train)

SVC(kernel='linear')

In [64]:
rbf_model.score(x_test,y_test)

0.9796296296296296

#### Just look into what is kernel

#### Kernel Function is a method used to take data as input and transform it into the required form of processing data. “Kernel” is used due to a set of mathematical functions used in Support Vector Machine providing the window to manipulate the data