## Exercise

- Take the iris flower dataset and using different classifiers randomforest, logistic regression, svm, decision tree
- using cross_val_score method, to measure the performance of best classifier
- find which model performs the best

In [4]:
# we'll import packages
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

import numpy as np

# let's import the iris datasets
from sklearn.datasets import load_iris
iris = load_iris()

In [31]:
from sklearn.model_selection import cross_val_score

In [43]:
lr_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
lr_scores

C:\Users\ezhil\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [44]:
svm_scores = cross_val_score(SVC(), iris.data, iris.target)
svm_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [45]:
rf_scores = cross_val_score(RandomForestClassifier(), iris.data,iris.target)
rf_scores

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [35]:
# let' average these things

In [46]:
lr_scores.mean()

0.9733333333333334

In [47]:
svm_scores.mean()

0.9666666666666666

In [48]:
rf_scores.mean()

0.96

In [30]:
# comparing to three models LogisticRegression model has more score with 97.33% accuracy